### ISSUE TITLE
SaveAs没有任何效果，可能是什么情况

### ISSUE THREAD

**Issue by TSSSS4** [JohnYang1210/PycomCAD#4]

**Comment by JohnYang1210** [comment]
你说的`SaveAs`应该是win32com底层的API，它至少需要一个文件输出路径，如果只是简单的类似于"test.dwg"文件名，那么另存的"test.dwg"就在你写的python脚本的路径下另存为这个dwg文件。

pycomcad的保存文件有两个API，一个是，`SaveFile（）`这个相当于对cad文件进行`contr+s`保存，还有一个是`SaveAsFile(filepath)`实际上是另存为。

**Comment by TSSSS4** [comment]
> 你说的`SaveAs`应该是win32com底层的API，它至少需要一个文件输出路径，如果只是简单的类似于"test.dwg"文件名，那么另存的"test.dwg"就在你写的python脚本的路径下另存为这个dwg文件。
> 
> pycomcad的保存文件有两个API，一个是，`SaveFile（）`这个相当于对cad文件进行`contr+s`保存，还有一个是`SaveAsFile(filepath)`实际上是另存为。

我用的就是pycomcad的两个保存API，但是都没有效果

**Comment by JohnYang1210** [comment]
没有遇到过这种问题，请贴下你的代码和脚本文件夹的截图

**Comment by TSSSS4** [comment]
![pyautocad – toolbox py PyCharm 2021_5_30 17_44_21](https://user-images.githubusercontent.com/29810939/120099571-c0320900-c16e-11eb-9210-f22e77fa02aa.png)
目前用的就是首页的例程

**Comment by JohnYang1210** [comment]
目前最大的可能是，第9行开Early Bind模式。
初次运行pycomcad，是默认的lazybind模式，第9行打开了EarlyBind模式，此时程序自动调用makepy.py文件，（本程序终止，所以第9行以后的程序都不执行，你当然可以在最后加个print测试，再运行，如果没有print内容，那肯定是这个原因）弹出select library控件，需要选中cad版本，点击确定，才能完成开启Earltbind模式，所以你可以看看有没有弹出该控件。

**Comment by TSSSS4** [comment]
确实是EarlyBind的问题，没有弹出select library控件，直接运行makepy.py会报错：

`(autocad) E:\work\pyautocad>python E:\software\Anaconda3\envs\autocad\Lib\site-packages\win32com\client\makepy.py
Traceback (most recent call last):
  File "E:\software\Anaconda3\envs\autocad\Lib\site-packages\win32com\client\makepy.py", line 387, in <module>
    rc = main()
  File "E:\software\Anaconda3\envs\autocad\Lib\site-packages\win32com\client\makepy.py", line 362, in main
    rc = selecttlb.SelectTlb()
  File "E:\software\Anaconda3\envs\autocad\lib\site-packages\win32com\client\selecttlb.py", line 146, in SelectTlb
    import pywin.dialogs.list
  File "E:\software\Anaconda3\envs\autocad\lib\site-packages\Pythonwin\pywin\dialogs\list.py", line 1, in <module>
    from pywin.mfc import dialog
  File "E:\software\Anaconda3\envs\autocad\lib\site-packages\Pythonwin\pywin\mfc\dialog.py", line 7, in <module>
    import win32ui
ImportError: DLL load failed while importing win32ui: 动态链接库(DLL)初始化例程失败。`

**Comment by TSSSS4** [comment]
[问题解决了，原因是pywin32-228版本和python3.9兼容有问题，详见](https://stackoverflow.com/questions/64655079/cannot-import-from-pywinauto-importerror-dll-load-failed-while-importing-win32)

目前改成了python3.6和pywin32-227，可以正常使用

**Comment by JohnYang1210** [comment]
select library控件一般在IDE编辑器的后面，你再好好找找，有可能已经打开了，你再去运行makepy. py就会出错，如果确实没有，现阶段可以注释掉9，26，23行（early bind对枚举值常数有影响），应该就可以运行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月30日(周日) 晚上6:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JohnYang1210/PycomCAD] SaveAs没有任何效果，可能是什么情况 (#4)




 
确实是EarlyBind的问题，没有弹出select library控件，直接运行makepy.py会报错：
 
(autocad) E:\work\pyautocad&gt;python E:\software\Anaconda3\envs\autocad\Lib\site-packages\win32com\client\makepy.py Traceback (most recent call last): File "E:\software\Anaconda3\envs\autocad\Lib\site-packages\win32com\client\makepy.py", line 387, in <module&gt; rc = main() File "E:\software\Anaconda3\envs\autocad\Lib\site-packages\win32com\client\makepy.py", line 362, in main rc = selecttlb.SelectTlb() File "E:\software\Anaconda3\envs\autocad\lib\site-packages\win32com\client\selecttlb.py", line 146, in SelectTlb import pywin.dialogs.list File "E:\software\Anaconda3\envs\autocad\lib\site-packages\Pythonwin\pywin\dialogs\list.py", line 1, in <module&gt; from pywin.mfc import dialog File "E:\software\Anaconda3\envs\autocad\lib\site-packages\Pythonwin\pywin\mfc\dialog.py", line 7, in <module&gt; import win32ui ImportError: DLL load failed while importing win32ui: 动态链接库(DLL)初始化例程失败。
