### ISSUE TITLE
关于按readme示例运行后与预期不符的情况

### ISSUE THREAD

**Issue by LawlietLau** [JohnYang1210/PycomCAD#7]
安装readme中示例代码复制粘贴后未在cad中得到任何图形，但弹出一个“Select Library"窗口，请问需要怎样才能让cad窗口中出现图像

![Snipaste_2023-02-26_14-50-40](https://user-images.githubusercontent.com/98534955/221396761-3f485024-0c42-4841-b070-4c7903ecbdb9.png)

**Comment by Sinlory** [comment]
可以看下原作者的帖子，里面有说明：
https://www.cnblogs.com/johnyang/p/12521301.html

**Comment by LawlietLau** [comment]
非常感谢能帮助解决我的问题，现在我在尝试学习通过civil 3d的dynamo板块做脚本，可能暂时用不上这个库的相关内容，再次表达谢意
